version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
  - nuget restore source\SixFourThree.BoxPacker.sln
build:
  project: source\SixFourThree.BoxPacker.sln     # path to Visual Studio solution or project
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: dV15ZHq6Bo60o+5WbnhVsNa6kVpfpJ92UiSYBFg8n7J/wwQd+M49t+uGXMi2ibIZ
  skip_symbols: false
  artifact: /.*\.nupkg/
